"""Initial migration

Revision ID: 0690969657e6
Revises: 237311595cbf
Create Date: 2025-05-24 14:55:07.707997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0690969657e6'
down_revision = '237311595cbf'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
