"""final model setup

Revision ID: 0bbe31a9d4ec
Revises: 112ec4ff7e91
Create Date: 2025-05-24 14:12:07.595879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bbe31a9d4ec'
down_revision = '112ec4ff7e91'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('id_supplier', sa.Integer(), nullable=False),
    sa.Column('nama_supplier', sa.String(), nullable=False),
    sa.Column('kontak', sa.String(), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_supplier', name=op.f('pk_supplier'))
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_user', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('barang',
    sa.Column('id_barang', sa.Integer(), nullable=False),
    sa.Column('nama_barang', sa.String(), nullable=False),
    sa.Column('kategori', sa.String(), nullable=True),
    sa.Column('stok', sa.Integer(), nullable=True),
    sa.Column('harga', sa.Float(), nullable=True),
    sa.Column('tanggal_masuk', sa.Date(), nullable=True),
    sa.Column('id_supplier', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_supplier'], ['supplier.id_supplier'], name=op.f('fk_barang_id_supplier_supplier')),
    sa.PrimaryKeyConstraint('id_barang', name=op.f('pk_barang'))
    )
    op.drop_index(op.f('my_index'), table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    op.create_index(op.f('my_index'), 'models', ['name'], unique=True)
    op.drop_table('barang')
    op.drop_table('users')
    op.drop_table('supplier')
    # ### end Alembic commands ###
