"""final model setup

Revision ID: 237311595cbf
Revises: 3c030082ee1e
Create Date: 2025-05-24 14:46:44.885373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237311595cbf'
down_revision = '3c030082ee1e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
