"""final model setup

Revision ID: 3c030082ee1e
Revises: 0bbe31a9d4ec
Create Date: 2025-05-24 14:16:00.163979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c030082ee1e'
down_revision = '0bbe31a9d4ec'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
